src/Entity/Currency.php
<?php

    namespace App\Entity;

    use Doctrine\ORM\Mapping as ORM;

    /**
     * @ORM\Entity(repositoryClass="App\Repository\CurrencyRepository")
     */
    class Currency
    {
        /**
         * @ORM\Id()
         * @ORM\GeneratedValue()
         * @ORM\Column(type="integer")
         */
        private $id;

        /**
         * @ORM\Column(type="string", length=255)
         */
        private $business_name;

        /**
         * @ORM\Column(type="decimal", precision=8, scale=5, nullable=true)
         */
        private $USD;

        /**
         * @ORM\Column(type="decimal", precision=8, scale=5, nullable=true)
         */
        private $EUR;

        /**
         * @ORM\Column(type="decimal", precision=8, scale=5, nullable=true)
         */
        private $GBP;

        /**
         * @ORM\Column(type="datetime")
         */
        private $create_date;

        public function getId(): ?int
        {
            return $this->id;
        }

        public function getBusinessName(): ?string
        {
            return $this->business_name;
        }

        public function setBusinessName(string $business_name): self
        {
            $this->business_name = $business_name;

            return $this;
        }

        public function getUSD()
        {
            return $this->USD;
        }

        public function setUSD($USD): self
        {
            $this->USD = $USD;

            return $this;
        }

        public function getEUR()
        {
            return $this->EUR;
        }

        public function setEUR($EUR): self
        {
            $this->EUR = $EUR;

            return $this;
        }

        public function getGBP()
        {
            return $this->GBP;
        }

        public function setGBP($GBP): self
        {
            $this->GBP = $GBP;

            return $this;
        }

        public function getCreateDate(): ?\DateTimeInterface
        {
            return $this->create_date;
        }

        public function setCreateDate(\DateTimeInterface $create_date): self
        {
            $this->create_date = $create_date;

            return $this;
        }
    }

src/Controller/CurrencyController.php
<?php
    /**
     * Created by PhpStorm.
     * User: yemre
     * Date: 2.02.2019
     * Time: 21:07
     */

    namespace App\Controller;

    use App\Services\CurrencyThereServices\CurrencyThereService;
    use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
    use Symfony\Component\HttpFoundation\Response;

    class CurrencyController extends AbstractController
    {
        public function index()
        {
            $service = new CurrencyThereService();

            $response = json_encode($service->get());

            return new Response(
                $response,
                Response::HTTP_OK,
                ['Content-Type', 'application/json']
            );
        }
    }

src/Controller/HomeController.php
<?php
    /**
     * Created by PhpStorm.
     * User: yemre
     * Date: 2.02.2019
     * Time: 12:39
     */

    namespace App\Controller;

    use App\Entity\Currency;
    use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
    use App\Services\{
        CurrencyOneServices\CurrencyOneService,
        CurrencyTwoServices\CurrencyTwoService,
        CurrencyThereServices\CurrencyThereService
    };

    class HomeController extends AbstractController
    {
        public function index()
        {
            $currencyOneService = new CurrencyOneService();
            $currencyTwoService = new CurrencyTwoService();
            $currencyThereService = new CurrencyThereService();

            $currenciesOne = $currencyOneService->get();
            $currenciesTwo = $currencyTwoService->get();
            $currenciesThere = $currencyThereService->get();

            $currencies = $this->comparing([ $currenciesOne, $currenciesTwo, $currenciesThere ]);

            $currenciesAll = $this->getDoctrine()
                ->getRepository(Currency::class)
                ->findAll();

            return $this->render('home.html.twig', [
                'currencies' => $currencies,
                'currenciesAll' => $currenciesAll,
            ]);
        }

        private function comparing($arrays = [])
        {
            if (!isset($arrays[0])) {
                return [];
            } elseif (!isset($arrays[1])) {
                return $arrays[0];
            };

            $arrayOne = $arrays[0];
            $arrayTwo = $arrays[1];

            $arrayOneCount = count($arrayOne);
            $arrayTwoCount = count($arrayTwo);

            if (($arrayOneCount === $arrayTwoCount) || $arrayOneCount > $arrayTwoCount) {
                $oneArray = $arrayOne;
                $twoArray = $arrayTwo;
            } elseif ($arrayTwoCount > $arrayOneCount) {
                $oneArray = $arrayTwo;
                $twoArray = $arrayOne;
            }

            foreach ($oneArray as $key => $value) {
                if (isset($twoArray[$key])) {
                    $currencies[$key] = $value < $twoArray[$key] ? $value : $twoArray[$key];
                } else {
                    $currencies[$key] = $value;
                }
            }

            if (isset($arrays[2])) {
                $arrays = array_splice($arrays, 2, 2);
                $currencies = $this->comparing(array_merge([$currencies], $arrays));
            }

            return $currencies;
        }
    }

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/home.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title> Currency App </title>
    <style type="text/css">
        @import url(https://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100);

        body {
            background-color: #3e94ec;
            font-family: "Roboto", helvetica, arial, sans-serif;
            font-size: 16px;
            font-weight: 400;
            text-rendering: optimizeLegibility;
        }

        .main {
            max-width: 800px;
            width: 100%;
            margin: 0px auto;
        }

        h3 {
            color: #fafafa;
            font-size: 30px;
            font-weight: 700;
            font-style: normal;
            font-family: "Roboto", helvetica, arial, sans-serif;
            text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.1);
            text-transform:uppercase;
        }

        .cheap-currencies {
            list-style-type: none;
            margin: 0;
            padding: 0;
        }

        .cheap-currencies li {
            background: white;
            display: block;
            float: left;
            width: calc(90.2% / 3);
            padding: 13px;
            text-align: center;
            vertical-align: middle;
            font-weight:300;
            font-size:16px;
        }

        .cheap-currencies li:first-child {
            border-bottom-left-radius: 5px;
            border-top-left-radius: 5px;
        }
        .cheap-currencies li:last-child {
            border-bottom-right-radius: 5px;
            border-top-right-radius: 5px;
        }

        .currencies {
            background: white;
            border-radius:3px;
            border-collapse: collapse;
            width: 100%;
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.1);
            animation: float 5s infinite;
        }

        th {
            color: white;
            background: #0072ec;
            border-bottom: 2px solid #c1c3d1;
            border-right: 1px solid #c1c3d1;
            font-size:18px;
            font-weight: 400;
            padding:14px;
            text-align: center;
            text-shadow: 0 1px 1px rgba(0, 0, 0, 0.1);
            vertical-align:middle;
        }

        th:first-child {
            border-top-left-radius:3px;
        }

        th:last-child {
            border-top-right-radius:3px;
            border-right:none;
        }

        tr {
            border-top: 1px solid #C1C3D1;
            border-bottom-: 1px solid #C1C3D1;
            color:#666B85;
            font-size:16px;
            font-weight:normal;
            text-shadow: 0 1px 1px rgba(256, 256, 256, 0.1);
        }

        tr:first-child {
            border-top:none;
        }

        tr:last-child {
            border-bottom:none;
        }

        tr:nth-child(odd) td {
            background:#EBEBEB;
        }

        tr:last-child td:first-child {
            border-bottom-left-radius:3px;
        }

        tr:last-child td:last-child {
            border-bottom-right-radius:3px;
        }

        td {
            background:#FFFFFF;
            padding: 13px;
            text-align: center;
            vertical-align:middle;
            font-weight:300;
            font-size:16px;
            text-shadow: -1px -1px 1px rgba(0, 0, 0, 0.1);
            border-right: 1px solid #C1C3D1;
        }

        td:last-child {
            border-right: 0px;
        }

        .mb-2 {
            display: flow-root;
            margin-bottom: 2rem !important;
        }

    </style>
</head>
<body>
    <div class="main">
        <h3>Currency App</h3>
        <div class="mb-2">
            <ul class="cheap-currencies">
                {% for key,currency in currencies %}
                    <li>{{ key }} : {{ currency }} </li>
                {% endfor %}
            </ul>
        </div>
        {% if currenciesAll %}
            <table class="currencies">
                <thead>
                    <tr>
                        <th>BUSINESS NAME</th>
                        <th>USD</th>
                        <th>EUR</th>
                        <th>GBP</th>
                        <th>DATE</th>
                    </tr>
                </thead>
                <tbody>
                    {% for currencies in currenciesAll %}
                        <tr>
                            <td> {{ currencies.businessName }} </td>
                            <td> {{ currencies.usd }} </td>
                            <td> {{ currencies.eur }} </td>
                            <td> {{ currencies.gbp }} </td>
                            <td> {{ currencies.createDate | date('d.m.Y H:i:s') }} </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif  %}
    </div>
</body>
</html>